export const C3 = `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH"""""""""""MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH9""?\`......-((++<>????>++++((-....._?7""HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB"^_...(<>>>>>>>>>>>>???????????????????=======1+-...?""MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB"!...(;;;;;>>;>>>>>>>>>??>>?>????>????????===?===========l=lz(..~"WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB"!..(;:;;;;;;;;>>>>><<>>>>?>>???????! ..+????==============lllll=lllllli-.-"WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9= .(;;;:;;;;;;;;;>>;>>>>>. <>?>??>?????\`   .???=<?!~??=======l===l=llllllllllllli..?TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB= .(;;;:;;;;;;;;;;>>>;><<>>>>>_ <>??>???>???  (????==+?<_ .=====lv???1l=lllllllltlltttttz-.?WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"!._;;;:;;;;;:;;;;;;;;>;\` !..>>>>>< .???????????\` (=?==z\` .(_ .====l! .(+.Jlllllllltltttlttttttt&..TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"\`.(::::;:;:;:;;;;;<<;;>>;>_  >>>>>>>< .??>??>?????-.(?==?=-   . .==l=1  +llllllllv!\`\`??ltttttttttttrto-.TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"\`.(::::;;;:;;;;;;;<\` .. (>>>><  <>>>?>?: +??????????????=?========l==lll=i. ~!1llllv  ?11 .ttttttttrtrtrrtrO-.TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM@!.(:::;:;:;:;;;:;;;;;\` !\` .(>;>>>_..>>?>??>?????????????===?=========l=l==ll=llllllllll .O(..,tttttttrtrtrrrrrrrro.,TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH= .:::::::;<<:;:<<;;;;;;_  !<! (>>>>>>>?>??>?????>????????=?===========l=l=ll=llllllllllltz..\`?tttttttttrtrrtrrrrrrrrrro.?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM@'.(::::::;;:<  (! .  <;;;;;<-..(>>>>>>>>?>??>???><<<?!!\`\`............. _~!??<<1llllllllllttlttttttttttttrrtrtrZ?1rrrrrrrrvvw.,TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD\`.:::::::;::;:;<.  ;;_  (;;>>>;>>>>>>>>>?>?<<?!\`...((+????????============l===z+(..._??1ztltttltttttttttrtrtrrrr: ,rZCrrvvvvvvvvi.TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD .::::::::\`(;:;;;;;.  ;;<..;>>;>>>>>>>>><!~ ..(??????????=?==?=============l=lllllllllllz+-..??1tttttttrtrrtrrrrr> .C!  ,vvvrvvvzzzzo.TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD .:::::::::;. <;:;:;;;- .;;;;>;>>;>>><!! .(<?>??????????????=?===========l=llllllllllllllllltlltO+..?1Otttrttrtrrtr- \`.J!.r7\`.Ovvzzzzzzzo.TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMD\`.::::::::::;:<. ~;;;;;;;;;>;;>>>;><<\`..(>>?>?????????????=?==?===========l=l=l=l=lllllllllltlttltttttt&..?1Orrrrrrrrrwwr{ ? ..vvzzzzzuzzuuzo.TMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMB!.:::::::::::;;:;;-  ~<;;;;>;>>>>><!\`.(>>>?>?>??>????????????==?==?========ll=ll=lllllllllzz1<>>>>?>?11zzOttr&..?zrrrrrrrvro..Jvvzzzzzzuzzuuzuuui.WMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMM^.~::::::::::;;:;;;;;;<-.;;;;;>;><! .<>>>>>?>????>???????????==?============ll=lllllllllllv<>>>>>>>>?>>?>??????1zOO-.?Orrrrvvvvvvvzzzzzuz?7XuzuuuuuX,/MMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMD _::::::::::;:;:;:;:;;;;;;;;;>><! .<>>>>?>?>??>??????????????==?===========ll=l=ll=llllllllz>>>>>>?>?>??>????????????zz-.?Ovvrvvvvzzzzw777w- ?uzuuuuuun.TMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMH'.::::::::::<<:;;:;;;;;;;;;;;;><\`.(>>>>>?>>?>?????>??????????==?===========l=l=lll=llllllllllz>>>>>>?>?>?????>??????????==?i._Cvvvzzzzuz} .+,_\` yuuuuuuuuu+,MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMF (:::::::::~ .(<<<;;;;;;;;;;;;! .>>>>>>>>>?>??>?>????????????==?===========ll=ll=lllllllllllttllz+>>?>?>??>???????????===?====1-.7zzzzzzuz&._\` .JuuuuuuuuuuZn.TMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMM^.::::::::::;  ~    ;;;;;;;;;<!.->>>>>>>>??>??>??????????????==?===========ll=ll=lllllllllllttlttttttz+????????>??????=??==========-.?wzuzuuzuo.JuuuuuuuuuZZZuZu,/MMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM#\`.:::::::::::;<-(:!\`.;;;;;;;<!.(>;>>>>>>>?>>??>???>??????????====?=========l==l=lllllllllllttlttltttttttttzzz?????????=?==?==?======ll<.?Xuzzuuuuuuuuuu^\`?4ZuZZZZZn.MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMF (::::::\` (<:;::;;_.(;;;;;;;! (>>;>>>>>>?>>??>??????????????==?=?=========ll=llll=lllllllllttlttttttttttttrtrttOzz????=?============l==ll-.?Xuuuuuuuu71X..n.(ZZZZZZZn.UMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMD ::::::::::_  ~<;;:;;;;;;;;! ,>;>>>>>>>>?>??>??>??>?????????==?===========l==lll=llllllllltltltttttttttrtrrtrrrrrrrrOzz==?==?=======ll=l=lll-.juzuuuuul T) OG+ZZZZZZZyX,7MMMMMMMMMMMMMMM
MMMMMMMMMMMMMM$.::::::::::;:<-   (;;;;;;;<\`.>;>>>>>>>>?>>??>??????????????==?===========ll=lll=lllllllllltttttttttttttttrtrrtrrrrrrrrrvrOz========ll==lll=lllz.(Ouuuuuun...dZZZZZZZZZZZZ,?MMMMMMMMMMMMMM
MMMMMMMMMMMMM%.::::::::::;;;;;;<.;;;;;;;! (>>>>>>>>>>?>??>??>???????<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<1111zzzzzzztttttttrrtrrtrrrrrrrrrrvrvvvvOz===l=l=llllllllllli ?XuuuZZuZZZZZZZZZZyyZyyZ+/MMMMMMMMMMMMM
MMMMMMMMMMMM%.::::::<\` _!:;:;:;;;;;;;;<\`.>>;>>>>>>>>?>??>???<<!\`                                             .tttttI                                _?<1llllllllO.(wuZZuZZZZZZZZZZZyZyyZyy;(MMMMMMMMMMMM
MMMMMMMMMMMt.:::::::::-.   ~<;;;;;;;;! (>>;>>>>>>>?>?>?><!\`                                                   tttttI                                      _?<ltttti jXZZZZZZZZZZyyyZyZyyyyy;JMMMMMMMMMMM
MMMMMMMMMMF.::::::<<:;< .<-..;;;;;;>!.<>>>>>>>>>>?>??<!\`                                                      tttrrI                                         -ttlttl.?XZZZZZZZZZZyZyyyyyyyyy,?MMMMMMMMMM
MMMMMMMMMF :::::::-    .;;;;;;;;;;;!.>>>>>>>>>>?>??<!                                                         ttrtrI                                          jtttttO.?XZZZZZyyX^    jyyyyyyW,UMMMMMMMMM
MMMMMMMM# (::::::;;;_.   _<;;;;;>;\`.>>>>>>>>>>?>?<!                                                           trtrrI                                          .ttttttO.(XZZZZZy\ .Xyn jyyyyVVk.HMMMMMMMM
MMMMMMMM!.:::::;::;;:;;;-.;;;;>;;\`.>>>>>>>>>?>??!                                                             ttrrrI                                           jttttttt-(XZyyZyn jyyyAJyyyVyVVh.MMMMMMMM
MMMMMMM%.::::;;:;;:;;;;;;;;;>;>>\`.>>>>>>>>>?>?>!                                             \`                rtrrrrrrvvvvvvvvzzzzzuzuuzuuuuuw.                (tttttrrt-(XyZyyyk.XyyyyyVVyVVVV[(MMMMMMM
MMMMMMF ;:;;:;:;;;;;;;;;;;>;;>;!.>>>>>>>>?>??<\`                             \`   \`       \`        \`            rrrrrrrrrrvrvvvvvvzzzzzzzuzzuzuuu{               (ttttrttrO.?yyZyyyyyyyyVVyVVVVVVW.WMMMMMM
MMMMMM\`(::;:;:;;:;;:;;;;;;;>>>:.;>>>>>>>?>?><\`             \`        \`   \`           \`                \`        rrrrrrrrrvrvvrvvvzzzzuzzzuzuzuzuu}               (rtrrtrrrrO.jyyyyyyyyV77?7WyVVVVfh.MMMMMM
MMMMMF.::;:;;:;;;;;;;;;;;>>;;; ;>>>>>>?>??>?\`                  \`                                              rrrrrrrvrvvvvvvzzzzzuzuzuzuuzuuuV\`               jrtrtrrrtrro 4yyyyyyf ..(, 4VVVffp;JMMMMM
MMMM# (:;:;;;;;;;;;;;;;;>>;>< (>>>>>?>?>?>?!            \`                      \`       \`   \`  \`               rrrrrrrrvvvvC777777777777777777!                .ZZwrrtrrrrrr>.yyyyyVr XVVf ,ffffpfk MMMMM
MMMM].:;:;:;:;;;;;;;;;>>;>>>!.>>>>>?>?????:                             .-+zlltllttttttttttttttrrrrrrrrrrrrrrrrrrrrrvvvvvv                                    ,yZZZwrrrrrrrd<(yyyVVy,    .dffpfpff)JMMMM
MMM#\`(:;;;;;;;;;;;;;;>;>>>>< >>>>??>??>?><                         \` .+lllllllllltlttlttttttttttttrrrrrrrrrrrrrrrrvvvvvvvv                                  .JZZyyZyZXwwwwXyk XyVyVVVVkwWfffffpfppR.MMMM
MMMF :;:;:;;;;;;;;;;>>>>>;>\`.>>>?>??>????:                 \`   \`   .+llllllllllltlllttltttttttrtrtttrtrrrrrrrrrrvvvvvvvvvz                                 .ZyZZyZyyyyyyyyyyy[,VVVVVVVVffffppfpfppp-dMMM
MMM:.;;;;;;;;;;;;;>>;>;>>>< >>?>??>??>??<              \`          .l=llllllllltlttttlttttttttrtrrrrrtrrrrrrrrvrvrvrvvvvzzz                                XZZyyZyyZyyyyyyyXU0I 4VVVVVVfffpfpfpfppppL,MMM
MM# :;:;;;;;;;;;>>;>>>>>>>~.??>?>??>????:          \`             .llllllllllltltlltttttttttrttrttrrrrrrrrrrrvrvvvvvvzzzzzz                                 ?XZyyZyyyyyyyy0vvvv;.zXVVffY7?!\`  fpppppW MMM
MMF ;;;;;;;;;;;>;>>>>>>>>< <>??>????????\`                        zl=llllllltlttlttttttttttttrrtrrtrrrrrrrrrvvrvvvvvzzzzzuz-                                  ?XyyyyyyyyyyWvvvzI wzzWffL..J&+.Wppfppp{JMM
MM\.;;;;;;;;;>>;>>>>>>>>>: >>?>???>????>                    \`   ,llllllllllltlttttttttttttrrtrrrrrrrrrrrrrvrvvvvvzzzzzzuzzzzzzuzuuuuuuZZZZZZZk,               ,yyyyyyyyVyykzzzw.jzzuWfpfWUVY ,pppppp],MM
MM\`(;;;;;;;>;>>>;>>>>>>>?~.????????????:                \`       llllllllllttlttttttttttttrrtrtrrtrrrrrrrrvvvvvvvzzzzuzzzuuzuuuuuuuuuuuuuZuZZZZZ.               yyyyyyyVyVVVkzzz{.uzuXpf.   ..dppppbbb.MM
M# ;;;;;;;>>;>>>>>>>>>>?> (??>??>??????\`                       .lllllllllttlttlttttttttrrtrrrrrrrrrrrrrrvvvvvvzzzzzzzuuzuzuuuuzuuuuuuZZuuZuZZZZ!               ZyyyyyVyVVVVyzuzl.uuzXpfppppppppppbbbR MM
M# ;;;;;>>;>>>;>>>>>>?>?< ?????????????            \`           ,lllllllttlttttttttttttrttrtrrrrrrrrrrrvvvvvvvzzzzuzuzzuzuuzuuuuuuuuuuZuZZZuZZZZ\`               XyyyVyVVVyVVVzzuI zuuXfppppppppppbbbbb MM
MF ;;;;>>;>>>>>>>>>?>>?>< ??>?????????<                        (llllltltttltttttttttrrtrrrrrrrrrrrrrrvvvvvvzzzzzzzuzuuzuzuuuuuuuuuuuZuZZuZZZZV^                XVyVyVVVVVVVVzuuI\`wuXfppppfWWpbbbbbbbb_dM
MF ;;>>;>>>;>>>>>?>>????< ?>?????????=>                 \`   \`  zllllttltttttttttttrtrtrrrrrrrrrrrrrvvvvvvvzzzzuzuzzuz{                                         yVVVVVyVVVffWzuzX zXppppW^    ?Wbbbbkk{dM
MF ;>>;>>>>>>>>>?>???>??: ?????????==?>                        zllttlttltttttttttrrtrrtrrrrrrrrrrrvvvvvvvzzzzzzuzuuuu)                                        .yyVVVVVVVffffkXuX.dppppp$ Jbbh (bbbkkk{JM
MF ;>>>;>>>>>>?>>??>????> ????????=?==>        \`               ztltttltttttttttrrttrtrrrrrrrrrrrvvvvvvvzzzzzuzzuzzuzu}                                        (VVVyVVVfffpfppfpp\`dppppph dpbR.Jbkkkkk{JM
MF >>;>>>>>>>?>???>???>?> ??????==?===>            \`           1tlltttttttttttrtrrrrrrrrrrrrrrrvvvvvvvzzzzuzzuuzuuuuu}                                        XVVVVVVfffpfpfpfpW Xpppppppbbbbbbbkkkkk:dM
M@ >>>>>>>>?>>??! .?????< ????==?==?==z                \`    \`  (ttttttttttttrrtrtrrrrrrrrrrrrvvvvvvvzzzzzuzzuzuuzuuuu}                                      .(VVVVVfffpfpffppppW Wpppppbbbbbbbkkkkkkk\`dM
M# ;>>>>>>?>????<(+?????? <?=?===?=====                        .tttttttttttrrtrrrtrrrrrrrrrvvvvvvvzzzzuzzzuuzuzuuuuuu:                                  ..dffVVVVfffpffpfppfpppP.pppppbbWYT4HkkkkkkkH MM
MN <>>>>>?>??>???????????.(?==?========.                        tttttttttrrtrtrrrrrrrrrrrrvvrvvvvzzzzzzuzuzzuuuuuuuuu:             \`  \`  \`  \`      ..&VVVVVVVVVVfffpfppfpppppfpt.pbbbbb= . . TkkkkqkK MM
MM;(>>>??>??>????>???????_.=?==========:                        jtttttttrttrrrrrrrrrrrrrvvvrvvvzzzzzuzzuuzuuuuuuuuuuuuuuZZZZZZZZyZyZyyyyyyyyyyyVVyyyVVVyyVyVVVfffpfpfpfpfpfpppp}(bpbbbR gK.b).kkkqkqD.MM
MM].>>?>??>????>????????=> ===========l>           \`    \`       .tttttrrtrrrrrrrrrrrrrrvvrvvvzzzzzuzzuzuzuuuzuuuuuuuuZuZuZuZZZZZZZZZZZZyyZyyyyyyyVyVyyVVVVVVVfffpfpfpfppppppppK XbbbbbW.d$ ! Jkkqkkk%-MM
MMb ?>??>??????????????=?=.<=========llz       \`            \`    <tttrtrrtrrtrrrrrrrrvvvvvvzzzzzzuzzuuzuuzuuuuuuuuuuuZZuZZZZZZZZyZyyyZyZyyyyyyyyyyVVVVVVVVVfffpfpfpfpppfppppppP.bbbbbbbkkHkWkkkqkqqk!dMM
MMN.<?>??>???????????=====:.========l==l-                         1trrtrrrrrrrrrrrrrvvrvvvzzzzzuzzuuzzuzuuuuuuuuuuuZZun_~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_Jpfppfpppppppp!JbbbbkkkkkkkkkqkkqkkK.MMM
MMM[.??>??????<!\`  ?1=??==1 1=====ll=lll1                          1rrtrrrrrrrrrrrvvvvvvvzzzzuzzzuzzuuuuuuuuuuuuuuZZuZZk-..~..~.~..~..~..~...~.~.~..~...~..~.~(dfpppfpppppppbP.bbbkkkHUWkkqkqkqkkqk%.MMM
MMMN ?????????\` .((. ======:.====l=ll=lll-             \`            ?rrrrrrrrrrrrvvrvvvzzzzzuzzuuzuuuuuuuuuuuuuuZZuZZZZZZ+~.~~.~~.~~.~~.~~.~~.~.~~.~~~~~.~~.~(Wfpppppppppppbb:(bbkbkK\`. ,HY4kqkqkkH\`dMMM
MMMM,(????????-.1?<: !\`(===1.<==l=l=ll=llz                 \`          ?OrrrrrrrvvvvvvvzzzzuzzzuzuuzuuzuuuuuuuuZZuZZuZZZZZZn_~.~~.~~.~~.~~.~~.~~.~~~..~.~~.~~(fppppfppppppbbbP.bkkkkkR W].H\`,kkqkqkP.MMMM
MMMMb ?????????!    ...+====> =lll=lllllll>        \`                     ?7COrvvvvvvzzzzzuzzuuzuzuuzzuXXVXXXVVXZZuZZZZZZZZZk-~.~.~.~~.~~.~~.~~.~.~.~~.~.~~-JfppfpppppppbbbbK\`dkbkkkH~   .!.Xkqkkqk!JMMMM
MMMMM,(??????=?++===========l-(llllllllllll-   \`               \`                                              (ZZZZZZZZZZZyZX/~.~~.~.~.~.~.~.~~.~.~~.~~.~(Xpppppppppppbbbbb\.bkkkkkkkqHm+gWkqkkqkP.MMMMM
MMMMMb 1????==?========1===l=z.<l=lllllllllt-           \`                                                     (ZZZZZZZZZyyZyyyo~~.~~~.~~~.~~.~.~~~.~~.~~(fppfpppppppbbbbbb%.bkkkkkqkqkqkkqkkqkqkH!dMMMMM
MMMMMM[.???==?==?=<?!   =ll=ll1 1lllllllllttt-                                                                (ZZZZZZZyZyZyyZyyn_~.~.~.~.~~.~~.~.~.~.~_JfppppppppppbbbbbbP.XbkkkkK"7TWkqkkqkkqkk%.MMMMMM
MMMMMMN.<==?==z\`?: ..(z==l=lllll 1llllllttltlt-             \`      \`                                          (ZZZZZZyyZyyZyyyyyk/~.~~.~~.~.~.~~.~~.~(dfpppfppppppbbbbbkf-dkkkkqki...  _74Hqkkqf.MMMMMMM
MMMMMMMb 1=====<.======ll=ll=llli.1llllttltttttl.               \`                                             (ZZZZyZyZyZyyyyyyyyyx~~.~.~~.~~.~.~.~~(WppppppppppbbbbbbkK_dkkkkkqkqkkqkm+..JkqkH!JMMMMMMM
MMMMMMMM[.=?======l=ll=lv?<lllllli.1lttlttttttttO.     \`                                 \`                    (yZZyyZyyyyyyyyyyyyVyn_~.~.~~.~~.~~._Jfpppfpppppbbbbbbkkf_dkkkkqkkqkqkkqqkkkkqkq\.MMMMMMMM
MMMMMMMMM,(======l=l=v!   .zlllllll 1tlttttttttttrO.                    \`   \`                \`                -ZZyyZyZyyyyyyyyyVyVVVk-~.~.~~.~~.~(dpppppppppbbbbbbbkkf-dkkkkqk=\`  .TqkkqqkkkqP.MMMMMMMMM
MMMMMMMMMN.<====l=l==  .lllv1lllllt1.<tttttttttttrrrO-.     \`       \`            \`               \`   \`        ,yyZyyyyyyyyyyyyVyVVVyVW+~~.~.~.~~(XpppfpppppbbbbbbkkkY.Xkkkqkq\.XP.+ qkqkkqqkP.MMMMMMMMMM
MMMMMMMMMMN.<==l=l=lli._<!  .+llttltO.?tttttttrrttrrrrrO-.                              \`                     ,yZyZyyyyyyyyyyVyVVVVVVVVo~~.~~.~(fppppppppbbbbbbbkkH=.Wkkqqkqk.gP X= dqkkqkkf_MMMMMMMMMMM
MMMMMMMMMMMN.1l=ll=lv?\`  .(llltltttttt-.zttttrtrrtrtrrrrrrrO(..                                               ,yyyyZyyyyyyyVyVVVyVVVffffh-~~._jpppppppppbbbbbbkkkK'.kkkqkkkkqkka...WkqkqkkK_dMMMMMMMMMMM
MMMMMMMMMMMMN.1l=lllz..+lllllttltlttttto.<ttrttrrrrrrrrrrrrrrrvvzwz+((.................   ....................,yZyyyyyyyyyVyVVVVVVVfffpfpW/~(dppppppppbbbbbbkkkkY.dkkkqkqkqkkqkkkkkkqkkqkK_dMMMMMMMMMMMM
MMMMMMMMMMMMMN.<l=lllllllllltl!\`_<ttttttO,(OtrrtrrrrrrrrrvvvvvvvvzzzzzuzuzuuuuuuuuuuuuZuZuuZZZZZZZZZZZZZZyyZyyyyyyyyyyyyVVVVVyVVVfffpfpffff&WpppppppppbbbbbkkkK^.kkkqkkqY"77Wkqqkqkqkkqkf_dMMMMMMMMMMMMM
MMMMMMMMMMMMMMN.<llllllltltv1O..z.(ttttttro.?rrrrrrrrrrrvrvvrvvvzzzzzuzzzuzuuuuuuuuuuuuZuZuuZuZZZZZZZZZyZZyyZyyyyyyyyyVyyVVVVVVVfffpfpfppppfppppppppbbbbbkkkH=.dkkkqkqk\.(.. ?kkqkqkqkkf.MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMN,?llllltlltl <} jo.ztttrrtrt<.1rrrrrrrrvvvrvvvzzzzzuzzzuuzuzuuuuuuuuZuZuZZZZZZZZZZZZZyyZyyZyyyyyyyyyyVVVVyVVVVfffpfpfpfppppppppppppbbbbbkkbY_(kkkqkkqf\` ?HkH .kkqkkqkqY.MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM,(llllttltlz...ztttttrttrrrrO..1rrrrrvrvvvvvzzzzzuzzuuzuuuuzuuuuuuuuZuZuZZZZZZZZZZZyZyyZyyyyyyyyyyVVyVVVVVVVfffpfpfpfppfppppppppbbbbbkkkY~.kkkkqkqkkkh,  ?~.XkqkqkkH=.MMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMp.1tltltttttttttttrrtOrrtrrrrw..1rrvvvvvvzzzzzuzzzuzzuzuuuuuuuuuuZZuZZZZZZZZZZZZZyZyZyyyyyyyyyyyVyVVyVVVVfffpfpfpfppppppppppppbbbbbkkY!.WkkqqkkqkqkqkqHa. .TkqkkqK'.MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMN,?tttttttttttv1rtZ! .Orrrrrrrw-.7vvvvvzzzzzuzzuuzuuuuuuuuuuuuuZuZZZuZZZZZZZZZyyZyyyZyyyyyyyyyVVyVVVVVVfffpfpfpfppfppppppppbbbbbkHY~.kkkkkqkqkkqkqkqkqkkk-dkkqqY.dMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMM,.zttttttttr<..\`  .rrrrrrrrrrvvi.?OvzzzzuzzuuzuuzuuuuuuuuuuuZZuZZZZZZZZZZZZyZyyZyyyyyyyyyyVVVVVVVVVfffpfpfpfpppppppppppbbbbbbV=.JkkkkkqkkqkqkkqkkkqkkqkkkqkH^.MMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMh.?ttttttrttri..rrrrrrrrrvvvvvvvn.-7zzuzzuzzuzuuuuuuuuuuuZuZuZuZZZZZZZZZyyZyZyyyyyyyyyyyVVyVVVVVVfffpfpfpppfppfppppppbbbbWY!.dkkkqkkqk94kqkqkkqkqkkqkqkqkY-gMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM,.1tttrrtrrrrrrrrrZ!\` _?wvvvvvzzz&.?CzuuuuzuuuuuuuuuuuZZuZZZZZZZZZZZZyZyyZyyyyyyyyyyVyVVVVVVVfffpfpfpfppfppppppppbbbWY^.+bkkkkqkqHY7  (WkqkqkqkqkkqkqK^.MMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMN,?OtrtrrtrrrrrrZ  .rw. OvvzzzzuzzX&.?7XuuuuuuuuuuuuZuZZuZZZZZZZZZyyZyZyyyyyyyyyyVVVVVyVVVVfffpfpfpppfppppppppbbWY^.JbkkkkkkkkqH\`.Wkn. 7kqkkkqkqkkH=.MMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMm.?rrrrrrrrrrrw..OrC  Jzzzzuzzuzuzzuu..?OuuuuuuuZZuZZZZZZZZZZZyZyZyyyyyyyyyyyyVyVVyVVVVfffpfpfpfppfppppppppY"~.dbkbkkHYWkkqkkH. 7HW'. .4kqkkqkqY-JMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMe.?trrrrrrrrrw-.  .JzzzzzOOzuuzuuzuuuX+._7TuuZZuZZZZZZZZZZyZyyZyyyyyyyyyyyVyVVyVVVVffffpfpfpppfpppppWY"~.JWbbkkkkkf .dkqkqkkH,. ..kh.JkqkqkY~.MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMe.1rrrrrrvvvvvvzzzzzuw\` .._OzuuuuuuuuuuX&..?7TXZZZZZZZyZZyZyyZyyyyyyyyyVyVVVVVVffffpfpfpfppppWY"!..+Wpbbbbkkkkkk] (4kkqkqqkqkkkqkkkkqkkY~.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMe.?rrvvvvvvzzzzzzzzXl.(Xi.uuuuuuuuuuZuZZuZX&-.-?7TUXyyZyyZyyyyyyyyyVVVVVVVVVfffpfppfWUY"^_..dWpbbbbbbbkkkkkkkkR (, ?4kkkqkqkqkqkqkkY~.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMa,?Ovvvvvzzzzuzuo.?= .uuuuuu=?TuuZuZuZZZZZZZZyZA+-.._~?777TTTUUUUUUUUUUVYT7"77!-...+dpppppppbbbbbbkkkkkkkkkqk..kH...WqkkqkkqkqH=(JMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,_CvzzzzuzzuzuzO((wuuuuu> .wuV?TZZZZZZZZZZZyZyZyZyyyyyXAA&+++JJJJ++&aAwWfffffppppppppppbbbbbbbkbkkkkkkkqkq[ dkkkqkqkqkqkk9=.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNJ.?wzuzzzuzuuzuuuuuuuI  duV\` (ZZZZZZZZyZyZyyyZyyZyyyyyyVVVVVVVVVVfffpfppfppppppppppbpbK"!\`?7HkkkkkkqqkkkHWqkqkkqkkkqHY~.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,_7zuuzuzuuuuuuuuun. ?7! .ZZZZZZl.. ?UZyZyyyyyyyyyVVyVVVVVVVfffpfppfppppppfppppbbbP .Wko .kkkkkqkkqqkqkkqkqkkqHY^.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMa,_7zuuuuuuuuuuuuZuun..ZZZZZZ!_?7C  yyyyy>\`\`?TyVyVVyVVVVffffUUWfpfff??'.  jbbbbbL .Wkf .kkkkqkkqkkqkqkkqkHY^.+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMa,_7XuuuuuuuZuZZZZZZZZZZZX..Uk: .yyyyyyyyl .VVVVVVVVfffpW  XfpppW  Xpb  bbbbbbn.. ..kkkqqkqkkqkkqkqHY^.+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,.?TuuuZuZuZZZZZZZZZZZZ&...JyyyyyyWyy% .VVyVVVVfffpfp_ dppppp; (pp. Obbbkkkkkkkkkqkkkqkqkkqk9"-.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNa,_74ZZZZZZZZZZZZZyyZyyyyyyyyyn.....XVVVVVfffpff"'. Jpfppph..bbmdWbbkbkkkkkqkqkqkqkkqU"!.JMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNg,.?TXZZZZZZyyZyyyyyyyyyyyyVVVVVVVVVVfffpfpn&WWWppppppppbbbbbbkkkkkkkqkqkkqkHY"<.+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNJ,_?7UyyZyZyyZyyyyyyVVyVVVVVVVfffpfpfppppppppppppbbbbbbbkbkkkkkkqk9Y"~..NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNg.._?7TUyyyyyyVyVVyVVVVVfffpfpfpfppppppppppbbbbbbkkkkkHYY"!..+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN+..-??7TTUWVVVVfffpfpfpfppfpppppppbbpWUYY"7!-..JgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNg+-.....-_<<??????<!~-(.....JggMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`;
